Public Class Activity

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' ActivityTableAdapter1.Fill(LexiconManagemnetToolsDataSet1.Activity)
    End Sub

    Private Sub ActivityBindingNavigatorSaveItem_Click(sender As Object, e As EventArgs) Handles ActivityBindingNavigatorSaveItem.Click
        Me.Validate()
        Me.ActivityBindingSource.EndEdit()
        Me.ActivityTableAdapter.Update(Me.LexiconManagemnetToolsDataSet.Activity)

    End Sub

    Private Sub XtraForm1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        'TODO: This line of code loads data into the 'LexiconRecManagerDataSet.PlanTypes' table. You can move, or remove it, as needed.
        Me.PlanTypesTableAdapter.Fill(Me.LexiconRecManagerDataSet.PlanTypes)
        'TODO: This line of code loads data into the 'LexiconRecManagerDataSet.Branch' table. You can move, or remove it, as needed.
        Me.BranchTableAdapter.Fill(Me.LexiconRecManagerDataSet.Branch)
        'TODO: This line of code loads data into the 'LexiconManagemnetToolsDataSet.Activity' table. You can move, or remove it, as needed.
        Me.ActivityTableAdapter.Fill(Me.LexiconManagemnetToolsDataSet.Activity)
        'TODO: This line of code loads data into the 'LexiconManagemnetToolsDataSet.Activity' table. You can move, or remove it, as needed.
        DevExpress.XtraSplashScreen.SplashScreenManager.CloseForm()


    End Sub
End Class